### PR TITLE
solves dependencies problem, endless loop 

### PR DESCRIPTION
**Pull request by mk01**
I suppose this needs fixing in mountall original code, but for the time being.

specific case like this:

fs                   mountpoint
zfs                  /zfs
zfs/home             /home
zfs/home/1           /zfs/test/1
zfs/test             /zfs/test

mountall ended up in an endless loop, waiting for dependencies. if mounts are read ordered by mount points, it's ok. 

at line 1329 in procedure mount_policy is a test for kernel filesystems (nodev) which puts parent device (prior processed entry) into dependencies, creating a loop in this example.

### CODE REVIEW

**Comment by dajhorn** [comment]
This should checked for side-effects involving dajhorn/pkg-zfs#63 and dajhorn/pkg-zfs#70.  Time permitting, I will do some testing this weekend.

The mountall logic for ordering records in a regular `/etc/fstab` file should be double-checked for appropriateness with ZFS.

**Comment by mk01** [comment]
i'm still trying to reproduce http://comments.gmane.org/gmane.linux.file-systems.zfs.user/5133. udevs are fired up quite late (after all virtual are mounted), but then devices are created and swapped correctly.

(finally managed to reproduce)

I think the swap story is exactly the candidate for patch like this https://github.com/dajhorn/pkg-zfs/issues/63 but not adding zfs to the filter, but "strcmp (((Mount *)mnt->entry.prev)->type, "swap")".

I can't think of a case, when a mountpoint should wait for swap. here is patch.  36995d5a6b055af95cb13bbaaa220b8981923cb7

**Comment by dajhorn** [comment]
Okay, thanks.

**Comment by mk01** [comment]
@dajhorn the same will happen for nfs, maybe others. and for nfs there is always a chance that won't be accessible during boot.

**Pull request closed without merging**
